kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
snd_driver_load="YES"
zfs_load="YES"
mac_do_load="YES"
autoboot_delay=5
boot_mute=YES
# Added by auto-admin from desktop-installer
uplcom_load="YES"
ng_ubt_load="YES"
acpi_ibm_load="YES"
cuse_load="YES"
# End auto-admin addition
