# Base config 
hostname="the-devil"
wlans_iwm0="wlan0"
ifconfig_wlan0="WPA DHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"
create_args_wlan0="country US regdomain FCC"

# Start services and modules
sshd_enable="YES"
ntpd_enable="YES"
powerd_enable="YES"
moused_nondefault_enable="NO"
kld_list="/boot/modules/i915kms.ko"
kld_list="i915kms fusefs"
zfs_enable="YES"
moused_port=/dev/psm0
moused_enable="YES"
ntpdate_enable="YES"
nfs_client_enable="YES"
rpc_statd_enable="YES"
rpc_lockd_enable="YES"
autofs_enable="YES"
devd_enable="YES"
dbus_enable="YES"
sddm_enable="YES"
webcamd_enable="YES"
sndbuf_enable="YES"

# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"

# Faster boot opts
rc_startmsgs="NO"

# Set flags
ntpdate_flags="-u pool.ntp.org"
devfs_system_ruleset="system"
webcamd_0_flags="-d ugen0.4"
allscreens_flags="-f 16x32 terminus-b32"
