# Client-side shadows
shadow = true;
shadow-radius = 12;
shadow-opacity = .55;
shadow-offset-x = -6;
shadow-offset-y = -6;

# Fade windows in/out
fading = true;
fade-in-step = 0.025;
fade-out-step = 0.025;
fade-delta = 5
# Transparency
frame-opacity = 1.0;
# Corners
corner-radius = 12;
# Blur
blur-size = 15;
blur-strength = 10;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-kern = "3x3box";

# General settings
dbus = true;
backend = "glx";
vsync = true;
use-damage = true;
