[window]
padding = { x = 8, y = 8 }
opacity = 0.85
blur = true

[font]
normal = { family = "ZedMono Nerd Font", style = "Regular" }
size = 16

# Gruvbox Material Dark-Medium Color Schema
[colors.primary]
background = '#282828'
foreground = '#d4be98'

[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[cursor]
style = { shape = "block", blinking = "on" }
blink_interval = 500
blink_timeout = 0

[mouse]
bindings = [
	{ mouse = "Right", action = "Paste" },
]

